### ISSUE TITLE
Tools not working

### ISSUE THREAD

**Issue by TobyDJackson** [julien-diener/CRtoolbox#1]
After loading up the GUI and locating the input video, none of the tools are working for me. Whichever one I click gives a set of error messages. Below are the errors generated by trying to run 'mask'. Has anyone had this problem too?

-------------------- Compute video mask --------------------
Improper index matrix reference.

Error in CRVideoAVI/readFromAvi (line 117)
            img = this.aviObject(ind).cdata;

Error in CRVideoAVI/getFrame (line 21)
img = this.readFromAvi( index );

Error in CRVideo/subsref (line 314)
                var = this.getFrame( s(1).subs{:} );

Error in crMask/computeMask_GUI (line 137)
    p.videoImg   = video(1);  % image of video in full depth (typically rgb)

Error in crMask (line 88)
computeMask_GUI();

Error in CRProject/run (line 194)
            computeFct(input,tool.parameters);

Error in CRProject/startGUI/runTool (line 169)
    this.run(tname);

Error while evaluating uicontrol Callback

**Comment by julien-diener** [comment]
This is a problem with the avi reader from matlab, I guess. The aviread function is not really good, so you should try to use image sequence instead, as stated in the [getting-started doc](https://sites.google.com/site/crtoolbox/Documentation/getting-started#TOC-Input-video). I updated the doc to provide a possible method using online converter. Can you convert  you video to an image sequence?

**Comment by TobyDJackson** [comment]
Thanks for your help, this works perfectly now.
