### ISSUE TITLE
Problem when starting GUI

### ISSUE THREAD

**Issue by A02l01** [julien-diener/CRtoolbox#2]
Hello Julien, When I start the GUI (project.startGUI()) I got tons of errors : 
```
Undefined function 'isnan' for input arguments of type 'matlab.ui.control.UIControl'.

Error in GridBagLayout/add (line 116)
            if ~isnan(h)

Error in CRUIbox/createUIbox (line 38)
        b.data.layout.add(b.data.text, 1, 1, 'MinimumWidth', b.data.textWidth , 'Anchor', 'West');

Error in CRUIbox (line 53)
            this.createUIbox();

Error in CRProject/startGUI/createPanel (line 223)
    h.proj_name   = CRUIbox(  'parent',h.proj_panel,     'style','edit',...

Error in CRProject/startGUI (line 18)
createPanel();                   % make the GUI

Error in CRParam/subsref (line 275)
            if isequal(it,this), [varargout{1:nargout}] = builtin('subsref', it, s);
```
Have you an idea what causes these errors?
I got Matlab R2018a
Sincerly
Adelin

**Comment by julien-diener** [comment]
Most probably this code is obsolete :-\

I stop maintaining it several years ago. And actually I am not using matlab anymore. So I can't do much about it. 

I hope the computation code is still working but most probably the UI code is all broken. 
Thus you can try to do all the processing by code (without ui). Then if you fill like it, update the UI code. I would really appreciate that. 

Sorry
